### ISSUE TITLE
Allow setting of a working directory in rockcraft.yaml

### ISSUE THREAD

**Issue by gruyaume** [canonical/rockcraft#121]
Lots of software require the user to be in a given directory before the startup command can be called. As of Today, there is no way to set the working directory of a given rock, the default working directory being "/". This forces users to create an entrypoint (or cmd) that `cd's` in a given directory before calling the actual command). It would be great if a `working-directory` field was added to `rockcraft.yaml` that would set the working directory to the provided path.

Here's an example of how this could:
```yaml
name: magma-orc8r-nms-magmalte
version: "1.6.0"
base: ubuntu:18.04
summary: Magma Orchestrator NMS Magmalte
description: Magma Orcestrator NMS Magmalte
license: Apache-2.0
platforms:
  amd64:

cmd: ["/bin/yarn", "run", "start:prod"]
working-directory: "/usr/src/packages/magmalte/"
```

Expected behaviour:
- The `entrypoint` command is executed from the provided working-directory
- At run time, if you `exec` a command in the container, the working directory is the one provided in the `rockcraft.yaml` file.
- Ideally: The parts have access to this working directory through environment variables (ex. `$WORKING_DIRECTORY`).

**Comment by SamirPS** [comment]
Hello @gruyaume 

So today, this PR has been merged https://github.com/canonical/rockcraft/pull/305, which permits you to add a working dir for the service you want to launch.

Thanks to this, you can change your ``rockcraft.yaml`` file to: 

```yaml
name: magma-orc8r-nms-magmalte
version: "1.6.0"
base: ubuntu:18.04
summary: Magma Orchestrator NMS Magmalte
description: Magma Orcestrator NMS Magmalte
license: Apache-2.0
platforms:
  amd64:
services:
  test:
    override: replace
    command: /bin/yarn run start:prod
    startup: enabled
    working-dir: /usr/src/packages/magmalte/
```
