### ISSUE TITLE
`base: bare` + `overlay_packages` = unhelpful error message

### ISSUE THREAD

**Issue by mr-cal** [canonical/rockcraft#136]
### Issue
Defining a rock with `base: bare` and `overlay_packages` does not produce a useful error message.  

### Error

`Overlay environment execution error: [Errno 2] No such file or directory: 'apt-get'`

### Reproducer
```
name: hello-world
version: latest
build-base: ubuntu:20.04
base: bare
summary: Hello World
description: A Hello World rock
license: Apache-2.0
cmd: [/usr/bin/hello, -t]

platforms:
  amd64:
  
parts:
  hello:
    plugin: nil
    overlay-packages:
      - hello
```

### Output
```
Starting Rockcraft 0.0.1.dev1
Logging execution to '/home/developer/.cache/rockcraft/log/rockcraft-20221103-112142.847011.log'

Launching instance...
Starting Rockcraft 0.0.1.dev1
Logging execution to '/tmp/rockcraft.log'
Retrieving base bare
Retrieved base bare for amd64
Extracting bare:latest
Extracted bare:latest
Initializing parts lifecycle
Executing parts lifecycle
Overlay environment execution error: [Errno 2] No such file or directory: 'apt-get'
Full execution log: '/tmp/rockcraft.log'
craft-providers error: Failed to execute pack in instance.
Full execution log: '/home/developer/.cache/rockcraft/log/rockcraft-20221103-112142.847011.log'
```
