### ISSUE TITLE
Overlay contents might not be preserved between parts

### ISSUE THREAD

**Issue by tigarmo** [canonical/rockcraft#166]
It looks like the overlay dir is not being "preserved" between the `overlay-script` of different parts. This could be important if, for example, two distinct parts want to add users to the ROCK (while we don't have official user support).
Here's an example in a rock with an ubuntu base:

```yaml
  p1:
    plugin: nil
    overlay-script: |
      rm ${CRAFT_OVERLAY}/lib32

  p2:
    after: [p1]
    plugin: nil
    overlay-script: |
      mkdir ${CRAFT_OVERLAY}/lib32
```

So one part removes the base `lib32` symlink, and then the other part creates a `lib32` dir. I tried to do that in #163 but it failed with "lib32 already exists", but only in ubuntu-18.04. So this needs some investigating.
