### ISSUE TITLE
Provide more meaningful output when charmcraft.yaml is invalid

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/rockcraft#182]
Hi!

I've been trying to run `charmcraft pack` with a valid yaml wrongly indented:
```
name: Indico
summary: Indico rocks
description: Indico OCI images for the Indico charm
version: "1.0"
base: bare
build-base: ubuntu:22.04
license: Apache-2.0
platforms:
  amd64:
parts:
  indico:
    plugin: python
      python-packages:
        - indico==3.2.0
```
and I'm getting the following output:
```
Logging execution to '/home/arturo/.local/state/rockcraft/log/rockcraft-20230206-173725.594029.log'                                                                               
rockcraft internal error: ScannerError(None, None, 'mapping values are not allowed here', <yaml.error.Mark object at 0x7fddfe017610>)                                             
Full execution log: '/home/arturo/.local/state/rockcraft/log/rockcraft-20230206-173725.594029.log'                                   
```
I would have expected the output to show the affected line or element.
