### ISSUE TITLE
Support packages and slices as part of the same stage-packages

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/rockcraft#183]
Hi!

I've been trying to pack a rock having both packages and slices defined among the `stage-packages` but I'm getting the following error:
```
Cannot mix packages and slices in stage-packages in field 'parts.indico'
```

```
name: Indico
summary: Indico rocks
description: Indico OCI images for the Indico charm
version: "1.0"
base: bare
build-base: ubuntu:22.04
license: Apache-2.0
platforms:
  amd64:
parts:
  indico:
    stage-packages:
      - build-essential
      - ca-certificates_data
    source: plugins
    plugin: python
    python-packages:
      - indico==3.2.0
```

IMHO it would be nice to support both indistinctly.

Thank you
