### ISSUE TITLE
Rockcraft fails to use sources from parent directory

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/rockcraft#189]
Hi!

Due to the limitations described in #185, I've been unsuccessfully trying to pack a rock with the rockcraft.yaml in a subdirectory. Unfortunately, referring to sources in the parent directory doesn't seem to be supported. I've tried both `source: ../files`and `source: ./../files`:

`Failed to copy or link file tree: '/root/files' is not a directory`.

This could probably be fixed by using current execution directory for `rockcraft pack` as working directory (maybe that's already done) and implementing #185, so that the rocks descriptor can reference anything in the directory structure from which the command is executed.

Below are the rockcraft.yaml contents and the truncated directory structure.
```
name: indico-nginx
summary: Indico nginx rock
description: Nginx OCI image for the Indico charm
version: "1.0"
base: bare
build-base: ubuntu:22.04
license: Apache-2.0
platforms:
  amd64:
parts:
  add-user:
    plugin: nil
    overlay-script: |
      addgroup --gid 2000 nginx
      adduser --system --gid 2000 --uid 2000 --no-create-home --disabled-login nginx
  copy-config:
    plugin: dump
    source: ../files
    source-type: local
    prime:
      - etc/nginx/nginx.conf
```

```
arturo@arturo-seijas:~/indico-operator$ ls -R
.:
actions.yaml     docs               indico-nginx.Dockerfile          LICENSE        plugins           src
charmcraft.yaml  files              indico_rock                      load_tests     pyproject.toml    tests
CODEOWNERS       icon.svg           indico_ubuntu-20.04-amd64.charm  metadata.yaml  README.md         tox.ini
config.yaml      indico.Dockerfile  lib                              nginx_rock     requirements.txt  trivy.yaml

./files:
etc  start-indico.sh

./files/etc:
indico  nginx

./files/etc/indico:
indico.conf  logging.yaml  uwsgi.ini

./files/etc/nginx:
nginx.conf

./indico_rock:
rockcraft.yaml

```

Thank you
