### ISSUE TITLE
Building on Ubuntu with base bare image fails to add user and group

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/rockcraft#193]
Hi!

I currently have the following rockcraft.yaml where `rockcraft pack` is failing due to the files `/etc/group` and `/etc/passwd` not being present. Considering the I'm building on Ubuntu I would have expected those two files to be added to the bare image and staged.

```
name: indico-nginx
summary: Indico nginx rock
description: Nginx OCI image for the Indico charm
version: "1.0"
base: bare
build-base: ubuntu:22.04
license: Apache-2.0
platforms:
  amd64:
parts:
  add-user:
    plugin: nil
    overlay-script: |
      groupadd -R $CRAFT_OVERLAY --gid 2000 nginx
      useradd -R $CRAFT_OVERLAY --system --gid 2000 --uid 2000 --no-create-home nginx
```
Related to #23 

Thank you
