### ISSUE TITLE
Unable to import rock into the docker daemon when packing with python plugin and staging python3-dev

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/rockcraft#194]
Hi!

I've just noticed `skopeo` fails to import the resulting rock when packing with the python plugin:
```
name: indico
summary: Indico rock
description: Indico OCI image for the Indico charm
version: "1.0"
base: ubuntu:22.04
build-base: ubuntu:22.04
license: Apache-2.0
platforms:
  amd64:
parts:
  indico:
    stage-packages:
      - python3-dev
      - python3-venv
    source: plugins
    plugin: python
```
`skopeo --insecure-policy copy oci-archive:indico_1.0_amd64.rock docker-daemon:localhost:32000/indico:latest` seems to execute successfully but when I run `docker image ls` there are no results. However, it works if I change the plugin:
```
name: indico
summary: Indico rock
description: Indico OCI image for the Indico charm
version: "1.0"
base: ubuntu:22.04
build-base: ubuntu:22.04
license: Apache-2.0
platforms:
  amd64:
parts:
  indico:
    stage-packages:
      - python3-dev
      - python3-venv
    source: plugins
    plugin: nil
```
After some changes in my rockcraft.yaml to provide a narrower use case, I noticed the following does work with the python plugin, so this likely has to do with the staged packages, either python3-dev or pythone-venv:
```
name: indico
summary: Indico rock
description: Indico OCI image for the Indico charm
version: "1.0"
base: ubuntu:22.04
build-base: ubuntu:22.04
license: Apache-2.0
platforms:
  amd64:
parts:
  indico:
    stage-packages:
      - build-essential
    source: plugins
    plugin: python
```
Let me know if there's anything else you'd like me to provide in order to pinpoint the issue.

Thank you
