### ISSUE TITLE
LXD 5.0 fails to build rocks on Ubuntu 22.04

### ISSUE THREAD

**Issue by twovican** [canonical/rockcraft#195]
When using LXD 5.0 on 22.04, `rockcraft pack` will fail to build.  Throwing the following error:

`2023-02-14 17:59:07.565 :: 2023-02-14 23:59:06.997 fuse-overlayfs mountpoint='/root/overlay/overlay', args=('-olowerdir=/root/bundles/ubuntu-20.04/rootfs,upperdir=/root/overlay/packages,workdir=/root/overlay/work',)
2023-02-14 17:59:07.565 :: 2023-02-14 23:59:07.020 Failed to mount overlay on /root/overlay/overlay: Command '['fuse-overlayfs', '-olowerdir=/root/bundles/ubuntu-20.04/rootfs,upperdir=/root/overlay/packages,workdir=/root/overlay/work', '/root/overlay/overlay']' returned non-zero exit status 1.`

The current workaround is to upgrade LXD to 5.9 stable.

Run this:
`sudo snap install lxd --channel=5.9/stable`

Instead of this:
`sudo snap install lxd --channel=5.0/stable`

**Comment by gboutry** [comment]
I have the same errors using lxd 5.11/stable

```bash
2023-03-06 14:54:30.168 :: 2023-03-06 13:54:29.785 fuse-overlayfs mountpoint='/root/overlay/overlay', args=('-olowerdir=/root/bundles/ubuntu-20.04/rootfs,upperdir=/root/overlay/packages,workdir=/root/overlay/work',)
2023-03-06 14:54:30.168 :: 2023-03-06 13:54:29.817 Failed to mount overlay on /root/overlay/overlay: Command '['fuse-overlayfs', '-olowerdir=/root/bundles/ubuntu-20.04/rootfs,upperdir=/root/overlay/packages,workdir=/root/overlay/work', '/root/overlay/overlay']' returned non-zero exit status 1.
```

**Comment by sergiusens** [comment]
@tomponline can you help out with this?

**Comment by tomponline** [comment]
@sergiusens do you have reproducer steps (ideally not requiring and just the problem commands it is calling, or if not then for someone who is not familiar with rockcraft?) Thanks

**Comment by gboutry** [comment]
> @sergiusens do you have reproducer steps (ideally not requiring rockcraft and just the problem commands it is calling, or if not then for someone who is not familiar with rockcraft?) Thanks

I can't really give you steps without rockcraft, but with rockcraft:
In an empty dir, add `rockcraft.yaml`:
```yaml
name: my-rock-name
base: ubuntu:22.04
version: '0.1'
summary: summary
description: description
license: Apache-2.0
platforms:
    amd64:

parts:
    my-part:
        plugin: nil
        overlay-packages:
          - software-properties-common
```
Then, run `rockcraft -v pack`.

I ran this commands using: 
- rockcraft `installed: 0+git.63135d7 (633) 83MB classic`
- lxd `installed: 5.11-ad0b61e (24483) 149MB`

**Comment by tomponline** [comment]
Thanks!

Does it work with LXD 5.10? I'm trying to understand if this is a regression or a new bug? Thanks

**Comment by tomponline** [comment]
Also can you show me the `lxc config show <instance> --expanded` for the container rockcraft is using please?

**Comment by tomponline** [comment]
And the output of `uname -a` please.

**Comment by gboutry** [comment]
It also fails with lxd 5.10, did not try with 5.9 and I can't install it anymore.

Output of `lxc --project rockcraft config show rockcraft-my-rock-name-258206 --expanded`:
```yaml
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 22.04 LTS amd64 (buildd release) (20220426)
  image.label: buildd release
  image.os: ubuntu
  image.release: jammy
  image.serial: "20220426"
  image.type: tar.gz
  image.version: "22.04"
  raw.idmap: both 1000 0
  security.syscalls.intercept.mknod: "true"
  volatile.base_image: 5de93bcc5cddf2ede3e74f88c313deb056eab006dd131618a5d412dc4a5e5534
  volatile.cloud-init.instance-id: 14e6eade-1ec8-4052-9d23-6261ea469bfd
  volatile.eth0.hwaddr: 00:16:3e:34:df:d2
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":0,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1000001,"Nsid":1,"Maprange":999999999},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":0,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1000001,"Nsid":1,"Maprange":999999999}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":0,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1000001,"Nsid":1,"Maprange":999999999},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":0,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1000001,"Nsid":1,"Maprange":999999999}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
  volatile.last_state.ready: "false"
  volatile.uuid: a22997db-4890-44f1-a59e-7e50273972c4
devices:
  eth0:
    name: eth0
    network: lxdbr1
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```


Output of `uname -a` (reproduced the behavior on both):
- `Linux gboutry-bastion 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux` <-- this is a vm
- `Linux infinity-book 6.1.0-1009-tuxedo #11 SMP PREEMPT_DYNAMIC Tue Feb 21 19:40:50 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux` <-- this is my laptop

**Comment by tomponline** [comment]
Thanks. I'm wondering if its to do with this:

https://discuss.linuxcontainers.org/t/linux-6-1-lts-confirmed-but-no-fix-for-mknod-yet/16436

Although the kernel versions don't match.

Although:

>  As far as I can see this problem with interception is present on 5.15 kernel too.

https://discuss.linuxcontainers.org/t/linux-6-1-lts-confirmed-but-no-fix-for-mknod-yet/16436/15?u=tomp

**Comment by tomponline** [comment]
Do you think this is the same issue as https://discuss.linuxcontainers.org/t/linux-6-1-lts-confirmed-but-no-fix-for-mknod-yet/16436 @mihalicyn ?

**Comment by mihalicyn** [comment]
Hello everyone,

1. I don't think that it's related to mknod intercept, because here we are failing on the mount stage. And here we have overlayfs-fuse, but there we have in-kernel overlayfs.

2. I think it makes sense to patch this place https://github.com/canonical/craft-parts/blob/62c65491a55a2d6b59979d27b40bd325744ac5a9/craft_parts/utils/os_utils.py#L249 and replace `check_call` to `check_output` or something else (I'm not a python expert), that allows to catch stdout/stderr. Otherwise we can only try to guess what's happening here. But having more verbose logs can help to quickly determine where is the problem.

**Comment by tomponline** [comment]
Thanks!

**Comment by cmatsuoka** [comment]
I've played a bit with fuse-overlayfs in a plain jammy container and in the container created by Rockcraft, and the results are different.

If I just launch a jammy container with lxc 5.11 and run fuse-overlayfs, it works:
```
root@test-overlayfs:~# mkdir upper lower work
root@test-overlayfs:~# fuse-overlayfs -olowerdir=lower,upperdir=upper,workdir=work /mnt
root@test-overlayfs:~# echo $?
0
```

However, if I enter the rockcraft container (`rockcraft pull --shell`), create the directories and run the same command, it fails:
```
root@rockcraft-my-rock-name-2378573:~/project# fuse-overlayfs -olowerdir=lower,upperdir=upper,workdir=work /mnt
fuse: mount failed: Invalid argument
fuse-overlayfs: cannot mount: Invalid argument
```
Running it through strace shows:
```
root@rockcraft-my-rock-name-2378573:~/project# strace fuse-overlayfs -f -olowerdir=lower,upperdir=upper,workdir=work /mnt
execve("/snap/rockcraft/638/usr/bin/fuse-overlayfs", ["fuse-overlayfs", "-f", "-olowerdir=lower,upperdir=upper,"..., "/mnt"], 0x7ffc37889f58 /* 27 vars */) = 0
...
stat("/mnt", {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
openat(AT_FDCWD, "/dev/fuse", O_RDWR|O_CLOEXEC) = 6
getgid()                                = 0
getuid()                                = 0
mount("fuse-overlayfs", "/mnt", "fuse.fuse-overlayfs", MS_NODEV|MS_NOATIME, "default_permissions,allow_other,"...) = -1 EINVAL (Invalid argument)
```
@mr-cal, what are the container creation parameters currently being used in Rockcraft?

**Comment by tomponline** [comment]
Can we see `lxc config show <instance> --expanded` for each one please?

**Comment by cmatsuoka** [comment]
Here they are:

* Plain container
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 22.04 LTS amd64 (release) (20230302)
  image.label: release
  image.os: ubuntu
  image.release: jammy
  image.serial: "20230302"
  image.type: squashfs
  image.version: "22.04"
  raw.lxc: |
    lxc.mount.entry = tmpfs tmp tmpfs rw,nosuid,nodev,size=2G
    lxc.mount.entry = tmpfs var/tmp tmpfs rw,nosuid,nodev,size=2G
  volatile.base_image: 72565f3fbae414d317b90569b6d7aa308c482fdf562aaf0c2eaa6e50fa39747b
  volatile.cloud-init.instance-id: 0b1a09bb-f746-4812-8344-07a5955c32c0
  volatile.eth0.host_name: vethbb897c4f
  volatile.eth0.hwaddr: 00:16:3e:a5:c9:dd
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 064a8457-c7d5-4ed5-9536-e8562cc40452
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: fast
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

* Rockcraft container
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 22.04 LTS amd64 (buildd release) (20220426)
  image.label: buildd release
  image.os: ubuntu
  image.release: jammy
  image.serial: "20220426"
  image.type: tar.gz
  image.version: "22.04"
  raw.idmap: both 1000 0
  raw.lxc: |
    lxc.mount.entry = tmpfs tmp tmpfs rw,nosuid,nodev,size=2G
    lxc.mount.entry = tmpfs var/tmp tmpfs rw,nosuid,nodev,size=2G
  security.syscalls.intercept.mknod: "true"
  volatile.base_image: 5de93bcc5cddf2ede3e74f88c313deb056eab006dd131618a5d412dc4a5e5534
  volatile.cloud-init.instance-id: fd5f9784-b2cc-4785-9777-1cd31dc93919
  volatile.eth0.hwaddr: 00:16:3e:e2:63:e9
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":0,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1000001,"Nsid":1,"Maprange":999999999},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":0,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1000001,"Nsid":1,"Maprange":999999999}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":0,"Maprange":1},{"Isuid":true,"Isgid":false,"Hostid":1000001,"Nsid":1,"Maprange":999999999},{"Isuid":true,"Isgid":true,"Hostid":1000,"Nsid":0,"Maprange":1},{"Isuid":false,"Isgid":true,"Hostid":1000001,"Nsid":1,"Maprange":999999999}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: STOPPED
  volatile.last_state.ready: "false"
  volatile.uuid: 91c32aa6-e09f-4e90-92ee-bcb4eb7d1e40
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: fast
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
