### ISSUE TITLE
Add support for `craftctl get version`

### ISSUE THREAD

**Issue by jnsgruk** [canonical/rockcraft#20]
It would be useful to be able to grab the version of the ROCK being built as part of the various scripted sections in `rockcraft.yaml`. Something like:

```yaml
version: "2.4.5"

# ...

parts:
	some-part:
		plugin: nil
        override-pull: |
			wget -O /tmp/product.tar.gz "https://releases.megacoolvendor.com/product/$(craftctl get version)_linux.tar.gz"
```
