### ISSUE TITLE
Python plugin failing to find Python binary

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/rockcraft#225]
Hi!

I'm trying to build a rock that was succeeding last week but now I'm getting an error stating `No suitable Python interpreter found, giving up.`.
Has the python plugin interface changed or is this perhaps a regression?

Below is the failing snippet:
```
name: indico-nginx
summary: Indico nginx rock
description: Nginx OCI image for the Indico charm
version: "1.0"
base: bare
build-base: ubuntu:22.04
license: Apache-2.0
platforms:
  amd64:
parts:
  indico-files:
    build-packages:
      - build-essential
      - libpq-dev
      - python3-dev
      - python3-pip
    plugin: python
    source: .
    python-packages:
      - indico==3.2.0
    organize:
      lib/python3.10/site-packages/indico/web/static: srv/indico/static
    stage:
      - srv/indico/static
```

Thank you very much
