### ISSUE TITLE
Provide a simple, declarative way to provision users in the resulting OCI image

### ISSUE THREAD

**Issue by jnsgruk** [canonical/rockcraft#23]
Right now, one has to do something like the following:

```yaml
parts:
  non-root-user:
    plugin: nil
    overlay-script: |
      chroot $CRAFT_OVERLAY
      useradd -M -r my-user
```

Such a feature would likely need to provide some sort of language for describing UID, system user or not, home directory if required, shell, etc. An MVP might just be the ability to create system users with a given UID, since that is a very common use case.
