### ISSUE TITLE
issue with running Pebble client as nonroot user

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/rockcraft#238]
## How to reproduce

_rockcraft.yaml_

```yaml
name: test
version: latest
summary: test
license: Apache-2.0
base: ubuntu:22.04
run-user: confined_daemon
services:
  test:
    override: replace
    command: echo foo
    startup: enabled
platforms:
  amd64:

parts:
  my-part:
    plugin: nil
```

`rockcraft pack`

`skopeo copy oci-archive:test_latest_amd64.rock docker-daemon:test:latest`

```bash
$ docker run -u root test exec whoami
root
```

But it will fail when running with the default nonroot user:

```bash
$ docker run test exec whoami
error: cannot perform the following tasks:
- exec command "whoami" (fork/exec /usr/bin/whoami: no such file or directory)
```
