### ISSUE TITLE
usrmerge issue when using the Python plugin without provisioning Python

### ISSUE THREAD

**Issue by tigarmo** [canonical/rockcraft#246]
The following part will generate a ROCK where the `/lib64` symlink to `/usr/lib64` is broken:

```yaml
parts:
  flask-part:
    plugin: python
    source: "."
    python-packages:
      - flask
```

Adding Python (e.g. via `stage-packages: [python3-venv]`) fixes the issue.
