### ISSUE TITLE
Conditional parts

### ISSUE THREAD

**Issue by sanchezfdezjavier** [canonical/rockcraft#249]
Hi rockcraft!

During Kubeflow's Rocks 🪨 workshop I had the chance of building this [rock](https://github.com/canonical/katib-rocks/pull/8/files) and I realized It would be great to have a feature to have _conditional parts based on a given parameter_.

This rock It's meant to support two architectures: `amd64` and `ppc64le `, we must install specific dependencies for the latter. This is how it's handled in the [original Dockerfile](https://github.com/kubeflow/katib/blob/fcea7a36cb48f9f799de94de4da13f514d9c569d/cmd/suggestion/nas/darts/v1beta1/Dockerfile#L16).

I was thinking about something like Github actions' `if: <codition>` [feature](https://github.com/canonical/charmed-magma-orchestrator/blob/ba794bdd25ce86518f62eaa7fbcdf79df9b7d3ec/.github/workflows/integration-tests.yml#L30) for conditionally running steps within your workflows.

I imagine something like the following, where your if statement will determine whether or not your part will be included depending on  architecture, series, maybe cloud provider (if you have kernel specific requirements), or similar.

This will avoid the overhead of maintaining several rocks for different platforms, or having a bloated rock.

Let me know if that makes sense!

```yaml
...

 parts:
   
...

   entrypoint:
     if: <condition> # <-------- NEW ✨
     plugin: dump
     source: https://github.com/kubeflow/katib.git
     source-subdir: cmd/earlystopping/medianstop/v1beta1
     source-type: git
     source-tag: master
     organize:
       main.py: usr/bin/main.py
     stage:
       - usr/bin/main.py

...
```
