### ISSUE TITLE
Stage-packages fails at unpack_stage_packages when installing some packages

### ISSUE THREAD

**Issue by valentincanonical** [canonical/rockcraft#28]
```yaml
name: test
version: 1.0
base: ubuntu:20.04

parts:
  part1:
    plugin: nil
    stage-packages:
    - ca-certificates
```

this example _rockcraft.yaml_ fails with the following error while executing `rockcraft pack` (in the `unpack_stage_packages` function):

```sh
ValueError: '/root/parts/part1/install/etc/ssl/openssl.cnf' does not start with '/root/parts/part1/install/usr/lib/ssl'
```
See the full log [rockcraft-20220422-181812.655447.log](https://github.com/canonical/rockcraft/files/8542481/rockcraft-20220422-181812.655447.log).
