### ISSUE TITLE
Dedicated plugin for `deb-security-manifest`

### ISSUE THREAD

**Issue by sed-i** [canonical/rockcraft#438]
### What needs to get done

oci-factory's [IMAGE_MAINTAINER_AGREEMENT](https://github.com/canonical/oci-factory/blob/main/IMAGE_MAINTAINER_AGREEMENT.md#enable-security-monitoring) requires having a generic part in rocks that stage debs.

It would be super handy to have this as a plugin.

### Why it needs to get done

It could reduce boilerpalte from the brittle

```yaml
  deb-security-manifest:
    plugin: nil
    after:
      - alertmanager
      - ca-certs
    override-prime: |
      set -x
      mkdir -p $CRAFT_PRIME/usr/share/rocks/
      (echo "# os-release" && cat /etc/os-release && echo "# dpkg-query" && dpkg-query --admindir=$CRAFT_PRIME/var/lib/dpkg/ -f '${db:Status-Abbrev},${binary:Package},${Version},${source:Package},${Source:Version}\n' -W) > $CRAFT_PRIME/usr/share/rocks/dpkg.query
```

to the concise

```yaml
  deb-security-manifest:
    plugin: deb-security-manifest
    after:
      - alertmanager
      - ca-certs
```
