### ISSUE TITLE
support architecture-specific builds

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/rockcraft#49]
The goal is to support the syntax for a Rockstar to specify a list of “build” and “target” architectures, which would, in turn, result in one ROCK artefact per combination.

All of these ROCK artefacts combined would, later on, compose the multi-arch ROCK (each artefact is an OCI manifest).

---

## Spec

```yaml
# takes a map of labels. Each label produces one ROCK artefact
# dict[str, dict[str, obj]] (req)
platforms:
  # labels are free text, used as a default for build-on/build-for when needed
  # labels are included in the final ROCK artefact name, eg. my-rock_1.0_<label>.rock.
  # There must be at least one label within platforms
  amd64:
    # will build-on amd64, and build-for amd64
  foo:
    # same as the previous label "amd64" above, just a different ROCK artefact
    
    # the build environment architecture where Rockcraft CAN build the ROCK artefact
    # list (req if `build-for` is present): compatible with $GOARCH, 
    build-on: [amd64]
    # the target architecture(s) the ROCK will be built for.
    # both `base` and `build-base` must respect the provided architecture
    # list (opt): one of $GOARCH
    build-for: amd64
  arm:
    # `build-for` defaults to the valid architecture defined by the label "arm"
    build-on: [amd64, arm, arm64] 
  i386: 
    # ERROR: `build-on` must be present 
    build-for: i386   
  another-label:
    # build-for i386
    build-on: [amd64]
    build-for: i386:
  amd64:
    # ERROR: the label-defined arch differs from the one defined by `build-for`
    build-on: [amd64]
    build-for: arm64
```
