### ISSUE TITLE
Cannot easily skip `go mod download` with the `go` plugin

### ISSUE THREAD

**Issue by alnvdl-work** [canonical/rockcraft#510]
### What needs to get done

When building with the `go` plugin, it's currently impossible to skip `go mod download` without overriding the entire build script as follows:
```
parts:
  mypart:
    plugin: go
    source-type: local
    source: .
    override-build: |
      go install ./...
```

### Why it needs to get done

Skipping `go mod download` can be useful in cases where private dependencies were vendored before being passed to `rockcraft`.

I believe in reality this is related to `snapcraft`, but I'm reporting it here anyway, please move the issue if needed. See the `go` plugin at: https://github.com/canonical/snapcraft/blob/main/snapcraft_legacy/plugins/v2/go.py
