### ISSUE TITLE
[wishlist] separate stage-packages and stage-slices

### ISSUE THREAD

**Issue by yanksyoon** [canonical/rockcraft#785]
### What needs to get done

Related to: https://github.com/canonical/rockcraft/issues/183

Add a separate part for slices (slice) that is different from packages (apt).
The following stages would be additionally required:
- build-slices
- stage-slices

### Why it needs to get done

I have the following runtime slices/packages that are required:
slice: nodejs, npm, libpq5
debs: ca-certificates_data

It is intended to write a cleaner code to have them be within a single part for expressJS extension.

This was code which throws an error `Cannot mix packages and slices in stage-packages ...`:
```
parts:
    <expressjs-part>
        ...
        stage-packages:
        - ca-certificates_data
        - nodejs
        - npm
        - libpq5
```

In order to use both the slices and apt packages, I had to separate them out into different parts.

```
parts
    <expressjs-part>
        ...
    <runtime-deb-part>
        ...
    <runtime-slice-part>
        ...
```

However, since logically, they should belong within the same part, it would be nice for rockcraft to not throw an error but provide a separate step in which slices can be defined as well as packages. i.e.
```
parts:
    <expressjs-part>
        ...
        stage-packages:
        - ca-certificates_data
        stage-slices:
        - nodejs
        - npm
        - libpq5
```
