### ISSUE TITLE
different contents or permissions error

### ISSUE THREAD

**Issue by yanksyoon** [canonical/rockcraft#790]
### Bug Description

Hello team!
A follow up from the [Matrix thread](https://matrix.to/#/!NPPCseDHKRvSBMUEXN:ubuntu.com/$upouJFvo8bjWS08ZNTe9yDtELNuVPh4qbs-ue3vEbbM?via=ubuntu.com&via=matrix.org) regarding the error when trying to merge the `lib` directory together.

This requires a dummy package.json at the source/root directory.
```package.json
{
  "name": "app",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "cookie-parser": "~1.4.4",
    "debug": "~2.6.9",
    "express": "~4.16.1",
    "http-errors": "~1.6.3",
    "jade": "~1.11.0",
    "morgan": "~1.9.1"
  }
}
```

### To Reproduce

1. Create the files above (rockcraft.yaml, package.json).
2. rockcraft pack
3. error: `Detailed information: Parts 'test/runtime' and 'expressjs-framework/install' list the following files, but with different contents or permissions: lib`

### Environment

Ubuntu 22.04 LTS

### rockcraft.yaml

```yaml
name: demo
title: demo
version: '0.1'
summary: summary
description: lib dir issue demo
base: bare
build-base: ubuntu@24.04
platforms:
  amd64:
    build-on:
    - amd64
    build-for:
    - amd64
parts:
  test/install:
    plugin: npm
    npm-include-node: true
    npm-node-version: node
    source: .
    build-packages: []
    stage-packages:
    - bash_bins
  test/runtime:
    plugin: nil
    stage-packages:
    - libpq5_libs
```

### Relevant log output

```shell
N/A
```
