### ISSUE TITLE
rockcraft insists on rebuilding part that has not changed

### ISSUE THREAD

**Issue by nicolasbock** [canonical/rockcraft#812]
### Bug Description

Using these `rockcraft.yaml` parts:

```yaml
    patches:
        plugin: dump
        source: .

    mariadb:
        after:
            - patches
        plugin: cmake
        source: https://github.com/MariaDB/server.git
        source-type: git
        source-tag: mariadb-10.5.28
        build-packages:
            - bison
            - ccache
            - gnutls-dev
            - libncurses5-dev
            - zlib1g-dev

    scripts:
        plugin: dump
        source: https://github.com/MariaDB/mariadb-docker.git
        source-type: git
        override-build: |
            ls -lh 
            install -D --mode 0755 10.5/docker-entrypoint.sh ${CRAFT_PART_INSTALL}/usr/bin/docker-entrypoint.sh
            install -D --mode 0755 10.5/healthcheck.sh ${CRAFT_PART_INSTALL}/usr/bin/healthcheck.sh
```

When I make any changes to the `scripts` part, the `mariadb` part is rebuilt. As far as I can tell, there is no dependency between `scripts` and `mariadb` that could invalidate `mariadb` in this scenario.

### To Reproduce

See the `rockcraft.yaml` snippet.

### Environment

Ubuntu 24.10

### rockcraft.yaml

```yaml
name: mariadb
base: ubuntu@24.04
version: "10.5"
summary: MariaDB database server and client
description: |
    MariaDB is a fast, stable and true multi-user, multi-threaded SQL database server.
    SQL (Structured Query Language) is the most popular database query language in the world.
    The main goals of MariaDB are speed, robustness and ease of use.
platforms:
    amd64:

parts:
    patches:
        plugin: dump
        source: .

    mariadb:
        plugin: cmake
        source: https://github.com/MariaDB/server.git
        source-type: git
        source-tag: mariadb-10.5.28
        build-packages:
            - bison
            - ccache
            - gnutls-dev
            - libncurses5-dev
            - zlib1g-dev

    scripts:
        plugin: dump
        source: https://github.com/MariaDB/mariadb-docker.git
        source-type: git
        override-build: |
            ls -lh
            install -D --mode 0755 10.5/docker-entrypoint.sh ${CRAFT_PART_INSTALL}/usr/bin/docker-entrypoint.sh
            install -D --mode 0755 10.5/healthcheck.sh ${CRAFT_PART_INSTALL}/usr/bin/healthcheck.sh
```

### Relevant log output

```shell
N/A
```
