### ISSUE TITLE
fastapi-framework extension cannot detect 'prime' entry from rockcraft.yaml

### ISSUE THREAD

**Issue by lego37yoon** [canonical/rockcraft#882]
### Bug Description

With `rockcraft.yaml` below, `ROCKCRAFE_ENABLE_EXPERIMENTAL_EXTENSIONS=true rockcraft pack` command which guided by official documents([1](https://documentation.ubuntu.com/rockcraft/en/stable/tutorial/fastapi/), [2](https://documentation.ubuntu.com/rockcraft/en/latest/reference/extensions/fastapi-framework/)) not worked as expected.

Requires 'prime' entry under 'parts' > 'fastapi-framework/install-app', but `rockcraft.yaml` already has.

### To Reproduce

1. Clone repository with this command in Multipass VM `git clone https://github.com/GDGoC-SCHU/Travia_BE`
2. `cd Travia_BE`
3. Init rockcraft file with `rockcraft init --profile fastapi-framework` 
4. Edit `rockcraft.yaml` file like below.
5. Run  `ROCKCRAFE_ENABLE_EXPERIMENTAL_EXTENSIONS=true rockcraft pack` script and get error message from rockcraft.

```bash
*EXPERIMENTAL* extension 'fastapi-framework' enabled
fastapi-framework extension requires the 'prime' entry in the fastapi-framework/install-app part to start with app/
For more information, check out: https://documentation.ubuntu.com/rockcraft/en/latest/reference/extensions/fastapi-framework
```

### Environment

- Running in Multipass VM
- Guest OS: Ubuntu 24.04 LTS
- Host OS: Kubuntu 24.10

- rockcraft : 1.11.0.post4+g22d0b2a (installed using snap)

### rockcraft.yaml

```yaml
name: travia-be
base: ubuntu@24.04
version: 0.1
summary: AI-based travel scheduler
description:
  Google Gemini based AI travel scheduler with Google Solutions Challenge
platforms:
  amd64:
  arm64:
extensions:
  - fastapi-framework
parts:
  fastapi-framework/dependencies:
    stage-packages:
      - mariadb-server
  fastapi-framework/install-app:
    prime:
      - .env
      - app/app.py
      - app/api/v1/endpoints
      - app/crud
      - app/db
      - app/models
      - app/schemas
      - app/services
      - gemini_api
```

### Relevant log output

```shell
Log not saved, but can get some error output from terminal:

*EXPERIMENTAL* extension 'fastapi-framework' enabled
fastapi-framework extension requires the 'prime' entry in the fastapi-framework/install-app part to start with app/
For more information, check out: https://documentation.ubuntu.com/rockcraft/en/latest/reference/extensions/fastapi-framework
```
