### ISSUE TITLE
Hello world tutorial doesn't work when using 24.04 base

### ISSUE THREAD

**Issue by seb128** [canonical/rockcraft#898]
### Bug Description

Trying to follow https://documentation.ubuntu.com/rockcraft/en/latest/tutorial/hello-world/#id1 but changing the base from 22.04 to 24.04 leads to an error

### To Reproduce

$ rockcraft pack
$ sudo rockcraft.skopeo --insecure-policy copy oci-archive:hello_latest_amd64.rock docker-daemon:hello:latest
$ docker run --rm hello:latest exec hello -t
error: cannot perform the following tasks:
- Execute command "hello" (fork/exec /usr/bin/hello: no such file or directory)

### Environment

On Ubuntu Plucky

$ rockcraft -V
rockcraft 1.12.0

### rockcraft.yaml

```yaml
$ cat rockcraft.yaml 
name: hello
summary: Hello World
description: The most basic example of a rock.
version: "latest"
license: Apache-2.0

base: bare
build-base: ubuntu@24.04
platforms:
  amd64:

parts:
  hello:
    plugin: nil
    stage-packages:
      - hello
```

### Relevant log output

```shell
$ docker run --rm hello:latest exec hello -t
error: cannot perform the following tasks:
- Execute command "hello" (fork/exec /usr/bin/hello: no such file or directory)
```
